### ISSUE TITLE
Certian sizes of mines have blocks filled with air.

### ISSUE THREAD

**Issue by glostone** [joserodpt/RealMines#17]
When i create a mine sized 4x4x3, And set the blocks to 20% and 80%, A single corner of the mine is air.

**Comment by JoseGamerPT** [comment]
Please show your mine.yml file and images from the in-game GUI

**Comment by glostone** [comment]
![image3](https://user-images.githubusercontent.com/85706815/201976831-e21674e9-6709-4476-a91e-20492df45e5c.png)
![image2](https://user-images.githubusercontent.com/85706815/201976835-ce163bc6-9e4f-43f7-a4e9-887283af4c32.png)
![image](https://user-images.githubusercontent.com/85706815/201976838-a2804425-9430-4325-b8d6-79dc43e302f4.png)
[config.yml.txt](https://github.com/JoseGamerPT/RealMines/files/10014554/config.yml.txt)
[mines.yml.txt](https://github.com/JoseGamerPT/RealMines/files/10014555/mines.yml.txt)

**Comment by JoseGamerPT** [comment]
<img width="151" alt="image" src="https://user-images.githubusercontent.com/18755024/201998380-46a8e0e7-365a-41a9-9538-49b25a3b65c1.png">
For some reason in your config the blocks have irregular numbers.
Change them to 
<img width="153" alt="image" src="https://user-images.githubusercontent.com/18755024/201998427-370cd994-d43f-4321-8d47-ff464eb96aa4.png">
and it should work!

**Comment by glostone** [comment]
The mine still has an air block in it

**Comment by JoseGamerPT** [comment]
Did you restart the server and made the config changes?
Try also to put 0.8 and 0.2

**Comment by toxicgamer111** [comment]
i have the same issue if its reseting everything is air
