### ISSUE TITLE
API for RealMines

### ISSUE THREAD

**Issue by neziw** [joserodpt/RealMines#18]

**Comment by neziw** [comment]
TODO:
- [ ] Events
- [ ] Static configuration in API
- [ ] Split RealMines into two modules like RealScoreboard
- [ ] Link maven repository to project

**Comment by JoseGamerPT** [comment]
Leave it open for when we have time

**Comment by joserodpt** [comment]
API is implemented beginning with the commit https://github.com/joserodpt/RealMines/commit/0f30ae0f0c737805687d932febdeb002b8fb627f
