### ISSUE TITLE
silent all

### ISSUE THREAD

**Issue by Bealang** [joserodpt/RealMines#19]
Komenda /rm silentall <kopalnia> służąca wyłączenie powiadomień w wszystkich kopalniach

**Comment by Bealang** [comment]
Make a new command /rm silentall, which turns off notifications about every mine resets

**Comment by neziw** [comment]
Feature being implemented, thanks

**Comment by joserodpt** [comment]
Feature added in this commit, thanks for the suggestion! https://github.com/joserodpt/RealMines/commit/5c8fb530a80ed27a833f6d04cd7ab6fb1daf9a05
