### ISSUE TITLE
Small bug. Wont let me set the reset percentage to 100, only 99. 

### ISSUE THREAD

**Issue by YodaZen** [joserodpt/RealMines#20]
As i have written in the title, the plugin doesn't let me set the reset percentage to 100, eventhough it says "Input a percentage greater than 1 and lower or equal to 100". 

MC-version: 1.18.2
Spigot: Paper
Plugin Version: 13-11-2022 Build 1

**Comment by joserodpt** [comment]
Fixed in this commit. Thanks! https://github.com/joserodpt/RealMines/commit/5c8fb530a80ed27a833f6d04cd7ab6fb1daf9a05
