### ISSUE TITLE
Cant set percentage of mines

### ISSUE THREAD

**Issue by begwars** [joserodpt/RealMines#21]
it gets stuck on this 
![image](https://user-images.githubusercontent.com/124471615/216792491-60c7b2f5-9a07-493b-9947-fec5c9a4f23c.png)

**Comment by joserodpt** [comment]
That alone doesn't tell us anything. 
Are there any errors in the console? What are you trying to change?

**Comment by neziw** [comment]
Just type cancel if you got stuck XD

**Comment by neziw** [comment]
We don't have any response from author of the issue, if you still have this problem then create new one.
