### ISSUE TITLE
Unhandled exception executing tab-completer for 'realmines create '

### ISSUE THREAD

**Issue by Togglerine** [joserodpt/RealMines#26]
Hello,

When i use command /realmines create (other also) - chat displays " an internal error occurred while attempting to tab-complete this command " and block of use it.
What can be cause of problem?

Console:

> [12:13:02] [Server thread/ERROR]: Exception when Togglerine attempted to tab complete realmines create 
> org.bukkit.command.CommandException: Unhandled exception executing tab-completer for 'realmines create ' in josegamerpt.realmines.mf.base.CommandHandler(realmines)
> 	at org.bukkit.command.SimpleCommandMap.tabComplete(SimpleCommandMap.java:246) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
> 	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.tabCompleteCommand(CraftServer.java:2271) ~[paper-1.19.4.jar:git-Paper-550]
> 	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.tabComplete(CraftServer.java:2243) ~[paper-1.19.4.jar:git-Paper-550]
> 	at org.bukkit.craftbukkit.v1_19_R3.command.BukkitCommandWrapper.getSuggestions(BukkitCommandWrapper.java:74) ~[paper-1.19.4.jar:git-Paper-550]
> 	at com.mojang.brigadier.tree.ArgumentCommandNode.listSuggestions(ArgumentCommandNode.java:71) ~[brigadier-1.0.18.jar:git-Paper-550]
> 	at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:601) ~[paper-1.19.4.jar:?]
> 	at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:581) ~[paper-1.19.4.jar:?]
> 	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleCustomCommandSuggestions$5(ServerGamePacketListenerImpl.java:913) ~[?:?]
> 	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.4.jar:git-Paper-550]
> 	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
> 	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
> 	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1342) ~[paper-1.19.4.jar:git-Paper-550]
> 	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.19.4.jar:git-Paper-550]
> 	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
> 	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1319) ~[paper-1.19.4.jar:git-Paper-550]
> 	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1312) ~[paper-1.19.4.jar:git-Paper-550]
> 	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
> 	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1290) ~[paper-1.19.4.jar:git-Paper-550]
> 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1178) ~[paper-1.19.4.jar:git-Paper-550]
> 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-550]
> 	at java.lang.Thread.run(Thread.java:833) ~[?:?]
> Caused by: java.lang.IllegalStateException: zip file closed
> 	at java.util.zip.ZipFile.ensureOpen(ZipFile.java:831) ~[?:?]
> 	at java.util.zip.ZipFile.getEntry(ZipFile.java:330) ~[?:?]
> 	at java.util.jar.JarFile.getEntry(JarFile.java:518) ~[?:?]
> 	at java.util.jar.JarFile.getJarEntry(JarFile.java:473) ~[?:?]
> 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:195) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:587) ~[?:?]
> 	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:155) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
> 	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:150) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
> 	at josegamerpt.realmines.mf.base.CompletionHandler.getTypeResult(CompletionHandler.java:114) ~[RealMines-1.1 (1).jar:?]
> 	at josegamerpt.realmines.mf.base.CommandHandler.tabComplete(CommandHandler.java:417) ~[RealMines-1.1 (1).jar:?]
> 	at org.bukkit.command.Command.tabComplete(Command.java:93) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
> 	at org.bukkit.command.SimpleCommandMap.tabComplete(SimpleCommandMap.java:240) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
> 	... 20 more

Thank you in advance

**Comment by joserodpt** [comment]
It seems like the plugin hasn't been properly loaded. Make sure that when you put new plugins or update existing ones, you properly restart the server. Reloading is known to cause bugs.

The error that points to what I said: 

> Caused by: java.lang.IllegalStateException: zip file closed
> at java.util.zip.ZipFile.ensureOpen(ZipFile.java:831) ~[?:?]
> at java.util.zip.ZipFile.getEntry(ZipFile.java:330) ~[?:?]
> at java.util.jar.JarFile.getEntry(JarFile.java:518) ~[?:?]
