### ISSUE TITLE
percentage not working

### ISSUE THREAD

**Issue by TheLovelyEmma** [joserodpt/RealMines#35]
I tried adding a block into the mine like I used to and it said to type the number in the chat and it never accepted it, it said to give a percentage from 0 to 1 for some reason and when I tried to cancel it, nothing happened.

This was on a paper 1.20.1 server.

**Comment by joserodpt** [comment]
Hi there. Can you provide additional logs and steps to reproduce the problem?

**Comment by joserodpt** [comment]
No further logs provided, closing issue.
