### ISSUE TITLE
Negative Block Count on Mine's Progress Bar

### ISSUE THREAD

**Issue by pepters** [joserodpt/RealMines#42]
![image](https://github.com/joserodpt/RealMines/assets/108479608/d92a4092-242d-4f01-810e-00a15179904f)
Errors appear after creating a certain number of mines
![image](https://github.com/joserodpt/RealMines/assets/108479608/19e4b070-e7a4-4d5d-9f27-99676510bcb7)

**Comment by pepters** [comment]
mines.yml file:
wreath:
  Icon: DIAMOND_ORE
  Teleport:
    X: 271.98279519477234
    Y: 76.25
    Z: 96.17509698590848
    Yaw: 127.68555
    Pitch: 26.699902
  Signs: []
  World: world
  POS1:
    X: 271.0
    Y: 78.0
    Z: 94.0
  POS2:
    X: 269.0
    Y: 76.0
    Z: 92.0
  Settings:
    Break-Permission: false
    Reset:
      ByPercentage: false
      ByTime: true
      ByPercentageValue: 20
      ByTimeValue: 60
      Silent: true
  Display-Name: wreath
  Faces: null
  Color: WHITE
  Type: BLOCKS
  Blocks:
    GREEN_GLAZED_TERRACOTTA:
      Chance: 1.0
Маяк:
  Icon: DIAMOND_ORE
  Teleport:
    X: 315.21090042507615
    Y: 44.0
    Z: 156.39065290437975
    Yaw: 305.5161
    Pitch: 13.799955
  Signs: []
  World: world
  POS1:
    X: 316.0
    Y: 43.0
    Z: 157.0
  POS2:
    X: 316.0
    Y: 43.0
    Z: 157.0
  Settings:
    Break-Permission: false
    Reset:
      ByPercentage: false
      ByTime: true
      ByPercentageValue: 20
      ByTimeValue: 1800
      Silent: false
  Display-Name: Маяк
  Faces: null
  Color: WHITE
  Type: BLOCKS
  Blocks:
    BEACON:
      Chance: 1.0
start1:
  Icon: DIAMOND_ORE
  Teleport:
    X: 282.7389613873773
    Y: 12.243139964954379
    Z: 158.98110223528772
    Yaw: 58.927734
    Pitch: 25.950085
  Signs: []
  World: world
  POS1:
    X: 280.0
    Y: 9.0
    Z: 177.0
  POS2:
    X: 272.0
    Y: 6.0
    Z: 161.0
  Settings:
    Break-Permission: false
    Reset:
      ByPercentage: false
      ByTime: true
      ByPercentageValue: 20
      ByTimeValue: 120
      Silent: true
  Display-Name: start1
  Faces: null
  Color: WHITE
  Type: BLOCKS
  Blocks:
    CRYING_OBSIDIAN:
      Chance: 0.3
    OBSIDIAN:
      Chance: 0.7
start2:
  Icon: DIAMOND_ORE
  Teleport:
    X: 352.98313947625854
    Y: 6.0
    Z: 159.73340192357603
    Yaw: -151.8244
    Pitch: 20.549925
  Signs: []
  World: world
  POS1:
    X: 354.0
    Y: 9.0
    Z: 156.0
  POS2:
    X: 346.0
    Y: 6.0
    Z: 140.0
  Settings:
    Break-Permission: false
    Reset:
      ByPercentage: false
      ByTime: true
      ByPercentageValue: 20
      ByTimeValue: 120
      Silent: true
  Display-Name: start2
  Faces: null
  Color: WHITE
  Type: BLOCKS
  Blocks:
    EMERALD_BLOCK:
      Chance: 0.3
    EMERALD_ORE:
      Chance: 0.7
start3:
  Icon: DIAMOND_ORE
  Teleport:
    X: 331.8878408844383
    Y: 19.251059505574286
    Z: 204.1086475463435
    Yaw: -140.42616
    Pitch: 22.499815
  Signs: []
  World: world
  POS1:
    X: 353.0
    Y: 9.0
    Z: 210.0
  POS2:
    X: 345.0
    Y: 6.0
    Z: 194.0
  Settings:
    Break-Permission: false
    Reset:
      ByPercentage: false
      ByTime: true
      ByPercentageValue: 20
      ByTimeValue: 120
      Silent: true
  Display-Name: start3
  Faces: null
  Color: WHITE
  Type: BLOCKS
  Blocks:
    DIAMOND_ORE:
      Chance: 0.7
    DIAMOND_BLOCK:
      Chance: 0.3
newbie:
  Icon: DIAMOND_ORE
  Teleport:
    X: 330.14923079155307
    Y: 102.0
    Z: -65.09009817801046
    Yaw: -310.94186
    Pitch: 11.0991125
  Signs: []
  World: world
  POS1:
    X: 332.0
    Y: 101.0
    Z: -56.0
  POS2:
    X: 320.0
    Y: 92.0
    Z: -68.0
  Settings:
    Break-Permission: false
    Reset:
      ByPercentage: false
      ByTime: true
      ByPercentageValue: 20
      ByTimeValue: 60
      Silent: true
  Display-Name: newbie
  Faces: null
  Color: WHITE
  Type: BLOCKS
  Blocks:
    EMERALD_ORE:
      Chance: 0.16
    EMERALD_BLOCK:
      Chance: 0.16
    OBSIDIAN:
      Chance: 0.16
    DIAMOND_BLOCK:
      Chance: 0.16
    DIAMOND_ORE:
      Chance: 0.16
    CRYING_OBSIDIAN:
      Chance: 0.2
tree:
  Icon: DIAMOND_ORE
  Teleport:
    X: 332.2675238139817
    Y: 83.0
    Z: 93.51697856709461
    Yaw: 75.862305
    Pitch: 29.999838
  Signs: []
  World: world
  POS1:
    X: 330.0
    Y: 85.0
    Z: 93.0
  POS2:
    X: 328.0
    Y: 83.0
    Z: 91.0
  Settings:
    Break-Permission: false
    Reset:
      ByPercentage: false
      ByTime: true
      ByPercentageValue: 20
      ByTimeValue: 100
      Silent: true
  Display-Name: tree
  Faces: null
  Color: WHITE
  Type: BLOCKS
  Blocks:
    LIME_GLAZED_TERRACOTTA:
      Chance: 1.0
penguin:
  Icon: DIAMOND_ORE
  Teleport:
    X: 382.35758436076566
    Y: 90.0
    Z: 151.83229146503174
    Yaw: 80.35693
    Pitch: 32.24982
  Signs: []
  World: world
  POS1:
    X: 380.0
    Y: 92.0
    Z: 154.0
  POS2:
    X: 378.0
    Y: 90.0
    Z: 152.0
  Settings:
    Break-Permission: false
    Reset:
      ByPercentage: false
      ByTime: true
      ByPercentageValue: 20
      ByTimeValue: 120
      Silent: true
  Display-Name: penguin
  Faces: null
  Color: WHITE
  Type: BLOCKS
  Blocks:
    BLACK_GLAZED_TERRACOTTA:
      Chance: 1.0
cake:
  Icon: DIAMOND_ORE
  Teleport:
    X: 377.5633526360918
    Y: 113.49390748022948
    Z: 190.24178983040485
    Yaw: 41.81201
    Pitch: 43.199894
  Signs: []
  World: world
  POS1:
    X: 379.0
    Y: 112.0
    Z: 194.0
  POS2:
    X: 377.0
    Y: 110.0
    Z: 192.0
  Settings:
    Break-Permission: false
    Reset:
      ByPercentage: false
      ByTime: true
      ByPercentageValue: 20
      ByTimeValue: 150
      Silent: true
  Display-Name: cake
  Faces: null
  Color: WHITE
  Type: BLOCKS
  Blocks:
    BROWN_GLAZED_TERRACOTTA:
      Chance: 1.0
snowman:
  Icon: DIAMOND_ORE
  Teleport:
    X: 330.6748514924233
    Y: 115.0625
    Z: 228.01524443119246
    Yaw: 336.70605
    Pitch: 25.304306
  Signs: []
  World: world
  POS1:
    X: 331.0
    Y: 117.0
    Z: 233.0
  POS2:
    X: 328.0
    Y: 115.0
    Z: 230.0
  Settings:
    Break-Permission: false
    Reset:
      ByPercentage: false
      ByTime: true
      ByPercentageValue: 20
      ByTimeValue: 60
      Silent: true
  Display-Name: snowman
  Faces: null
  Color: WHITE
  Type: BLOCKS
  Blocks:
    RED_GLAZED_TERRACOTTA:
      Chance: 1.0

**Comment by joserodpt** [comment]
Still waiting for a response.

**Comment by pepters** [comment]
Sorry, i forgot it. I noticed that this only happens when a certain number of mines are created. if I create a new one or delete any of them, there will be no error.

**Comment by pepters** [comment]
I don't have any schematic mines

**Comment by joserodpt** [comment]
Could you please create a case test with as many mines as you want, and if the error happens in a flat world, send me the mines.yml file? Thanks

**Comment by pepters** [comment]
Okay, I'll do it tomorrow
