### ISSUE TITLE
farm bug

### ISSUE THREAD

**Issue by qwseYT** [joserodpt/RealMines#43]
https://github.com/joserodpt/RealMines/assets/151243320/405464a2-51de-4df0-bd3b-87072ce98bad

I think words are unnecessary here, just watch the video

**Comment by joserodpt** [comment]
Indeed no words are needed. Thanks for reporting!

**Comment by joserodpt** [comment]
Happy to report that this issue has been fixed as of 11/01/2024 and it will be implemented in the upcoming 1.6.3 release! Thanks for Reporting!
Associated commit: https://github.com/joserodpt/RealMines/commit/eed4a4589dccc97b34de2829b87bd6ea612a0893
