### ISSUE TITLE
Percentage Bug

### ISSUE THREAD

**Issue by SkeloD** [joserodpt/RealMines#45]
So when i want to change the percentages of the block it wont let me and tell me 

Input a percentage from 0 to 1
Wrong input. Please input a percentage greater than 0

But i put "100" and "1".

and also when i want to search a block to add in my mine it just says 
Nothing found for your results

But i put oak for oak_logs but i can't find it.

**Comment by joserodpt** [comment]
> So when i want to change the percentages of the block it wont let me and tell me
Just tried with the latest version and it seems to work fine, couldn't replicate.

> and also when i want to search a block to add in my mine it just says
> Nothing found for your results
> But i put oak for oak_logs but i can't find it.

Also couldn't replicate this issue, please make sure you're using the most up to date version. Issue closed.
