### ISSUE TITLE
Impossible to set percentage of mine block by gui

### ISSUE THREAD

**Issue by Togglerine** [joserodpt/RealMines#46]
Hello,
Problem described in title
Screen: https://ibb.co/s5TL9tY

Any error log in console, only send this message from image on chat, when i write any numeric value

server engine is latest version of purpur

**Comment by joserodpt** [comment]
Hi there. Can't reproduce this, what steps did you take to reproduce it?

**Comment by Togglerine** [comment]
Write on chat /realmines mines -> next choose one of mine -> next choose Blocks (chest item in gui) -> next choose one of block of mine and when i click on it (https://ibb.co/FhKXcwv) and try to write on chat any value, but any is good and i have all the time on screen this : https://ibb.co/fMs0KSZ
I cant write "cancel" also because info on chat from first message screen is display

**Comment by joserodpt** [comment]
I continue to not be able to replicate that behaviour. 
It can be other plugins that are interfering with RealMines. What plugins do you have on your server?
Can you try a server with just RealMines installed?

**Comment by Togglerine** [comment]
Ok, thank you. I will give you response, when i find out what plugin is colidable

**Comment by joserodpt** [comment]
In the new update, there's an option in config to use a new GUI to set the percentages. Please give some feedback, thanks.

**Comment by Togglerine** [comment]
Works perfect, thank you!

**Comment by joserodpt** [comment]
Solved.
