### ISSUE TITLE
Bug makes the plugin useless

### ISSUE THREAD

**Issue by KingTurtle1000** [joserodpt/RealMines#47]
After I go to the panel it just randomly closes when i try to go into the blocks or icon selection pls help

**Comment by KingTurtle1000** [comment]
i also forgot to say that the resets panel still opens

**Comment by joserodpt** [comment]
Insuficient information, please provide more details and steps to reproduce the bug. Video and imagens can help.

**Comment by KingTurtle1000** [comment]
https://www.youtube.com/watch?v=dZ6FVGxVhuw

There's a video of the problem i am having. basically what is happening is when i do /rm panel and try to change the blocks in the mines the gui doesn't open but all the other ones do. It was working just fine a couple days ago before i updated all my plugins (including realmines) cause they were all a year old. I can send the console log in a bit once i get home

**Comment by joserodpt** [comment]
Please check if the problem persists if only RealMines is enabled.

**Comment by joserodpt** [comment]
No further comment from reporter.
