### ISSUE TITLE
Blocks broken unnaturally do not activate break actions and do not decrease percentage of the mine.

### ISSUE THREAD

**Issue by SydneysiderT** [joserodpt/RealMines#52]
Version: 1.20.4

By "unnaturally" I mean anything that isn't broken by a player. If I replace a section of the mine with air using worldedit, the break actions will not activate and neither will the mine percentage decrease.

**Comment by neziw** [comment]
This is completely normal behaviour since we are checking block break actions only.

**Comment by SydneysiderT** [comment]
Not to sound demanding but is it possible to make it an option? If you can't it's fine.

**Comment by joserodpt** [comment]
It can't be done, we're checking for PlayerBlockBreak event in the code, and external plugins don't trigger that event, sorry
