### ISSUE TITLE
ERROR message console: Cannot disable queue

### ISSUE THREAD

**Issue by matiasOliva64** [joserodpt/RealMines#55]
With version 1.7.6, the reset of the mines now works fine, but the console still shows the ERROR message: Cannot disable queue
![image](https://github.com/joserodpt/RealMines/assets/96148396/a66cd0a7-b944-4516-bfbc-ca3c2e61ff39)

**Comment by joserodpt** [comment]
Are you sure the error is comming from RealMines?
Do you have the latest FAWE/WE and Spigot/Paper?

**Comment by matiasOliva64** [comment]
With version 1.7.4 of realmines that error did not appear, later with version 1.7.5 that error appeared and the mines were not reset and with version 1.7.6 the mines are reset but that error appears. My version of Fawe is the latest and my version of Pepper is 1.20.1

**Comment by joserodpt** [comment]
If you could find steps to reproduce this issue, that would be very helpful, as currently I'm unable to replicate that error log.

**Comment by matiasOliva64** [comment]
ok, I'm going to test a little more, maybe it's not a plugin error, you can delete this issue.
