### ISSUE TITLE
error in block amount

### ISSUE THREAD

**Issue by pepters** [joserodpt/RealMines#56]
no errors in console
![Screenshot_6](https://github.com/user-attachments/assets/b0577016-e6f0-4478-8d45-279d86226c35)

**Comment by joserodpt** [comment]
Do you have the bounds properly set? Can you send your mines.yml file for that specific mine?

**Comment by pepters** [comment]
mine8:
  Icon: DIAMOND_ORE
  Teleport:
    X: 431.33027898275185
    Y: 159.0
    Z: 24.577850557613353
    Yaw: -289.44458
    Pitch: 21.45022
  Signs: []
  World: world
  POS1:
    X: 429.0
    Y: 162.0
    Z: 27.0
  POS2:
    X: 426.0
    Y: 159.0
    Z: 24.0
  Settings:
    Break-Permission: false
    Reset:
      ByPercentage: false
      ByTime: true
      ByPercentageValue: 20
      ByTimeValue: 460
      Silent: true
  Display-Name: mine8
  Faces: null
  Color: WHITE
  Type: BLOCKS
  Blocks:
    GREEN_GLAZED_TERRACOTTA:
      Chance: 1.0
  Reset-Commands: *id002

**Comment by pepters** [comment]
> Do you have the bounds properly set? Can you send your mines.yml file for that specific mine?

i think yes

**Comment by joserodpt** [comment]
Are you using any kind of server plugin that modifies block breaking / enchantments?
Does that negative number persist between server restarts?

**Comment by pepters** [comment]
Yes, executebleitems

**Comment by pepters** [comment]
I have pickaxes with mineincube action

**Comment by joserodpt** [comment]
Those kinds of plugins and items modify vanilla behaviour, and therefore are not supported.

**Comment by neziw** [comment]
Try without these plugins, If you still have same problem then create issue again or contact us via Discord Server.
