### ISSUE TITLE
Feature: rotate multiple mines inside one mine (rotating mines / rotating block sets)

### ISSUE THREAD

**Issue by dandud100** [joserodpt/RealMines#60]
It should be possible to rotate mines in a specific location. For example, after a mine has been reset (e.g., once 50% of its resources are mined), can a different, pre-configured mine appear in the same spot based on a set percentage? This way, different mines with varying compositions could randomly regenerate in the same location. That also could be announced in chat.

**Comment by joserodpt** [comment]
Working on this feature. To be released in version 1.8. Latest commit init https://github.com/joserodpt/RealMines/commit/bfd1733460696e38666a3def0eef7edf9d6886a3

**Comment by joserodpt** [comment]
Just implemented this feature. Please test it and give some feedback, thanks!
Please note that this is a 1.8 beta build.
[RealMines.jar.zip](https://github.com/user-attachments/files/17910695/RealMines.jar.zip)
