### ISSUE TITLE
Bug with worldedit and %realmines_minedblocks_mine%

### ISSUE THREAD

**Issue by pepters** [joserodpt/RealMines#61]
If you will place blocks in mine that is in worldedit region, placed blocks will add to  placeholder's value
I will provide record soon

**Comment by pepters** [comment]
Worldguard*, sorry

**Comment by joserodpt** [comment]
You place blocks in a region managed by world guard? Sorry, didn't quite understand your issue

**Comment by pepters** [comment]
Yes, i place a block in region and it momently dissapears because i am not allowed to place block there, but realmines counts it as broken block

**Comment by joserodpt** [comment]
That's because WorldGuard isn't linked to RealMines in any way.
If you're looking for a plugin like that, please take a look at RealRegions. It has RealMines compatibility and integration.
