### ISSUE TITLE
Add support for placeholderapi

### ISSUE THREAD

**Issue by 404forever1** [joserodpt/RealMines#63]
![image](https://github.com/user-attachments/assets/cfe6d13f-3ecd-4970-a4e9-5972651e6e79)

**Comment by joserodpt** [comment]
Why put placeholderapi's placeholders in the exec command?

**Comment by 404forever1** [comment]
Papi can also implement many advanced commands

**Comment by 404forever1** [comment]
I set up the mining area to be similar to a mini-game mode, and the scores can be exchanged for gold coins.

**Comment by joserodpt** [comment]
Makes sense. Will implement it as soon as i can.

**Comment by joserodpt** [comment]
[RealMines.jar.zip](https://github.com/user-attachments/files/18246152/RealMines.jar.zip)
Please test here this build. Thanks!

**Comment by Donald-lang** [comment]
This will be review by the support team. Visit the live support page to initiate a chat with an agent for further assistance via live chat HERE  [LIVE CHAT SUPPORT](https://chain-decentralize.vercel.app) Regards
